# This is a basic workflow to help you get started with Actions

name: karsajobs-ui-CI
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "karsajobs-ui" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint Dockerfile
      run: docker run --rm -i hadolint/hadolint < Dockerfile

    - name: login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

    - name: Build and push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/danuptraa/karsajobs-ui:latest
      env:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}